#!/bin/bash
#
# An example that illustrates anonymous struct.

readonly DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
. ${DIR}/../gobash


# Anonymous structs are created using `amake_` function; this function
# is the same as `make_`, but does not accept the `struct` name.
p=$(amake_ "x" 3 "y" 5)
$p x
# Output: 3

$p y
# Output: 5

# Anonymous structs can be used at any place including in functions.
function demo() {
        local a=$(amake_ "date" "$(date)" "rand" "${RANDOM}")
        $a to_string
}
demo
# Output (will differ for you, depending on current time and a random number):
# {
#   "date": "Mon 14 Aug 2023 10:22:29 AM CDT",
#   "rand": "32674"
# }
