#!/bin/bash
#
# while loop example.

# while loop executes the body of the loop as long as the condition is
# true; condition is a test (which return 0 or non-zero).

function main() {
        local sum=1
        while [ ${sum} -lt 1000 ]; do
                sum=$(( ${sum} + 1 ))
        done
        printf "Sum is ${sum}.\n"
}

main
